services:
  backend:
    container_name: nestjs_backend
    build: .
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - mysql_db
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    networks:
      - app_network

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=pass123
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql_db
    ports:
      - '8080:80' # Exposes phpMyAdmin on localhost:8080
    environment:
      PMA_HOST: mysql_db
      PMA_USER: user123
      PMA_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: pass123
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
