FROM node:20

# Set working directory
WORKDIR /app

COPY package.json ./

COPY package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3001

# มีการ build ก่อน รัน start:prod
RUN npm run build 

CMD ["npm", "run", "start:prod"]