// get customer
@localhost = http://localhost:5000/customers

###
get {{localhost}}/1 

###
get {{localhost}}


// create customer
###
post {{localhost}} HTTP/1.1
content-type: application/json

{ "name": "Angjel Joko", "address": "123 Street", "contact": "088888888", "email": "angjel@example.com" }


// update customer
###
put {{localhost}}/1 HTTP/1.1
content-type: application/json

{ "addressss": "1234563437890 Street", "contact": "088888888", "email": "john@example.com" }

// delete customer
###
delete {{localhost}}/1