// project
@localhost = http://localhost:3000/projects

###
get {{localhost}}

###
get {{localhost}}/4


// create project
###
post {{localhost}} HTTP/1.1
content-type: application/json

{
    "name": "container structure",
    "description": "container structure for the project of the company make it simple with the container structure implementation ",
    "customerId": 1,
    "projectItems": [
        {
            "itemId": 3,
            "quantity": 2
        },
        {
            "itemId": 2,
            "quantity": 4
        }
    ],
    "number": "P-0002",
    "startDate": "2025-03-01",
    "endDate": "2026-12-31"
}


// update project
###
put {{localhost}}/4 HTTP/1.1
content-type: application/json

{
    "name": "container structure11111",
    "projectItems": [
        {
            "itemId": 1,
            "quantity": 1,
            "price": 999999
        },
        {
            "itemId": 2,
            "quantity": 1,
            "price": 10000
        }
    ]
}

